### ISSUE TITLE
修改COOKIECLOUD相关参数会启动失败,窗口闪退.恢复成默认的就没事.

### ISSUE THREAD

**Issue by Bender1337** [developer-wlj/Windows-MoviePilot#1]
修改这两个参数会启动失败,窗口闪退.可以看到登录界面,但是登录失败.

    # CookieCloud用户KEY
    COOKIECLOUD_KEY: str = 
    # CookieCloud端对端加密密码
    COOKIECLOUD_PASSWORD: str = 

![微信截图_20230829151416](https://github.com/developer-wlj/Windows-MoviePilot/assets/54093431/b0f4ff79-fa94-4bf1-9184-dcdbb50847d4)

恢复成默认的就没事.

**Comment by developer-wlj** [comment]
只要不是数字类型和布尔类型，都需要加""
