### ISSUE TITLE
每次重启mp后，下载目录地址都会出现问题

### ISSUE THREAD

**Issue by xishi** [developer-wlj/Windows-MoviePilot#10]
每次重启完，下载目录会变，电影下载目录会变为空，如图：
![2024-03-11_08-58-17](https://github.com/developer-wlj/Windows-MoviePilot/assets/6111160/4f6cce69-b24f-42d1-8327-8c1b6cd7ded7)
查看appWindows,env时，文件下方会多出记录，每次保存都会多一条，但是重启后目录地址还是会变。

**Comment by xishi** [comment]
appWindows.env文件截图如下
![2024-03-11_09-09-17](https://github.com/developer-wlj/Windows-MoviePilot/assets/6111160/06656759-0842-47cd-bdec-c820b7e015cf)

**Comment by developer-wlj** [comment]
修改方法如下:
1. 退出应用程序
2. appWindows.env删除重复的变量
3. DOWNLOAD_PATH和LIBRARY_PATH, 或者其他目录变量, 在填写根目录时 要写成 `'E:'` 或`'E:/'` 不能写成`'E:\`, 否则就会出现你说的情况
