### ISSUE TITLE
关于使用edge最新版无法成功访问http://127.0.0.1:3000/的问题

### ISSUE THREAD

**Issue by asnfohsdgfbkxcv** [developer-wlj/Windows-MoviePilot#11]
已经成功启动了mp且logo运行正常，但是无法进入http://127.0.0.1:3000/，使用chrome也进不去。
![image](https://github.com/developer-wlj/Windows-MoviePilot/assets/8177108/5e5bb504-f988-449f-8ef9-794ed993ac10)
![image](https://github.com/developer-wlj/Windows-MoviePilot/assets/8177108/de7ad84c-98e0-43a2-8f4a-680715aa766a)
![image](https://github.com/developer-wlj/Windows-MoviePilot/assets/8177108/9b75a5fa-2728-43d3-8325-db6025b07aed)

**Comment by asnfohsdgfbkxcv** [comment]
请大佬不吝赐教，谢谢~~
看logo是正常运行的。
![image](https://github.com/developer-wlj/Windows-MoviePilot/assets/8177108/92b751d9-57ae-4a1a-a988-a14f7d01783c)

**Comment by developer-wlj** [comment]
1，运行后，任务栏有没有moviepilot的托盘图标
2，如果有安全卫士先退出，或者加入白名单，不然安全卫士回杀掉进程，拦截文件的
3， 如果是win11平台 多运行几次
4，再次启动，报缺少文件，就再次安装

**Comment by asnfohsdgfbkxcv** [comment]
感谢回复～
1.有托盘图标，运行成功了，mp的日志也能查到。
2.无360，有个火绒，未收到有拦截通知。我尝试一下添加目录为白名单后再反馈。【待确认】
3.确实是win11，x64。已经多次反复退出和重新启动程序了。重启过电脑也没用。
看readme说要用chrome，我用chrome也没用，还是进不去。
4.多次重新启动了也没有提示缺少文件。

**Comment by developer-wlj** [comment]
看情况 像是 3000端口 被其他服务顶掉了 
看下 在mp运行后 也有托盘图标 网页无法访问的情况下  查看3000端口 被哪个服务占用了

**Comment by asnfohsdgfbkxcv** [comment]
![image](https://github.com/developer-wlj/Windows-MoviePilot/assets/8177108/ff9c02a2-6fae-484c-b7fa-f7532cf3860b)
没有看到有在监听3000端口，是不是 nginx 没有运行的原因？？

**Comment by developer-wlj** [comment]
1，有没有nginx进程存活，本地是不是有多个nginx？
2，你是安装在什么目录
3，防火墙是不是没彻底关闭

**Comment by developer-wlj** [comment]
已修复nginx在中文目录不能启动的问题, 下载最新版本或[点击此链接](https://github.com/developer-wlj/Windows-MoviePilot/releases/tag/1.7.6-1.7a167b3) 前往下载
