### ISSUE TITLE
下载目录和媒体目录为多个文件夹时出错

### ISSUE THREAD

**Issue by 7s8x** [developer-wlj/Windows-MoviePilot#12]
下载目录和媒体目录为多个文件夹时出错，单个文件夹没有问题。
多目录设置如下，请问是哪里设置有误，谢谢大佬抽空解答。
![001](https://github.com/developer-wlj/Windows-MoviePilot/assets/119911589/ff2ec8f1-b767-436c-8f1e-1669b9509486)
![002](https://github.com/developer-wlj/Windows-MoviePilot/assets/119911589/d3cda2f3-bc57-462c-a883-aeb8ca6bf824)

**Comment by developer-wlj** [comment]
先了解下 mp的运行逻辑, 目前下载目录只支持一个, 媒体目录支持多个
