### ISSUE TITLE
MoviePilot无法访问网络挂载的驱动器

### ISSUE THREAD

**Issue by Laeoo** [developer-wlj/Windows-MoviePilot#13]
本地的C盘(C:\)可以正常访问
通过smb挂载的网络驱动器(U:\)无法正常访问
健康检查显示 媒体目录 - 错误！下载目录 U:\pt 不存在

**Comment by Laeoo** [comment]
【ERROR】2024-04-22 00:50:19,934 - filebrowser.py - 目录不存在：U:\/

**Comment by Laeoo** [comment]
【ERROR】2024-04-22 00:50:19,934 - filebrowser.py - 目录不存在：U:\/

**Comment by Laeoo** [comment]
【ERROR】2024-04-22 00:50:19,934 - filebrowser.py - 目录不存在：U:\ /  log里面显示这条

**Comment by Laeoo** [comment]
文件管理页面没有U:/这个路劲

**Comment by developer-wlj** [comment]
我这边测试没问题
你提供下截图
1 打开此电脑 截取挂载后相应盘符的图片
2 mp-设定-系统-媒体库相关设置图片
3 完整的报错日志

**Comment by testniubi1** [comment]
![1](https://github.com/developer-wlj/Windows-MoviePilot/assets/136640970/2f88aba2-ed6b-4cb4-98a9-b98216d40340)
![2](https://github.com/developer-wlj/Windows-MoviePilot/assets/136640970/58b2f51e-fd6a-4374-9bad-11644fd13f5d)
![3](https://github.com/developer-wlj/Windows-MoviePilot/assets/136640970/d5840695-6960-4f56-85e5-60c00b9333ab)
![4](https://github.com/developer-wlj/Windows-MoviePilot/assets/136640970/716bad3a-4faa-490b-a5c3-12039c63cf84)

**Comment by developer-wlj** [comment]
> ![1](https://private-user-images.githubusercontent.com/136640970/325718622-2f88aba2-ed6b-4cb4-98a9-b98216d40340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTI1ODEsIm5iZiI6MTcxNDA5MjI4MSwicGF0aCI6Ii8xMzY2NDA5NzAvMzI1NzE4NjIyLTJmODhhYmEyLWVkNmItNGNiNC05OGE5LWI5ODIxNmQ0MDM0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwMDQ0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzA5YWViYzFmMjIyZjEwZTFiNWExNWM2YzRhNjY4OTY3NDQ0YzljYmY3ZGQwMTcwODY2ZDRmZThiYzQ0MjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BzPSbL4Ma9frDCB0Kb5ilMNY9imYrD_aDSo_9G-Lv2A) ![2](https://private-user-images.githubusercontent.com/136640970/325718631-58b2f51e-fd6a-4374-9bad-11644fd13f5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTI1ODEsIm5iZiI6MTcxNDA5MjI4MSwicGF0aCI6Ii8xMzY2NDA5NzAvMzI1NzE4NjMxLTU4YjJmNTFlLWZkNmEtNDM3NC05YmFkLTExNjQ0ZmQxM2Y1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwMDQ0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjZkNWY2NTdlYWRmMDU5ZmI0YjlhNTUyYzE4OGFkYzJmNDcwMTI2ZGU2MTZlZTdiYmFkOTI4NzZmN2M4OTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AYJN9C5ydRuUGx75AJZrGiUPdD_jhovGy4q4HssaKOI) ![3](https://private-user-images.githubusercontent.com/136640970/325718635-d5840695-6960-4f56-85e5-60c00b9333ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTI1ODEsIm5iZiI6MTcxNDA5MjI4MSwicGF0aCI6Ii8xMzY2NDA5NzAvMzI1NzE4NjM1LWQ1ODQwNjk1LTY5NjAtNGY1Ni04NWU1LTYwYzAwYjkzMzNhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwMDQ0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmQ5NDUwNmUxM2Q0MzA3MzExN2JkYzM1YzczNDVjNWViMDdiNWJlY2Q4ZjMyMDU5NmU1MWU4MjE3Y2ZiNTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0hLDZwLsHYr9W6B2IvbLbbK0sZgGGVjoIWdpye91x0I) ![4](https://private-user-images.githubusercontent.com/136640970/325718637-716bad3a-4faa-490b-a5c3-12039c63cf84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTI1ODEsIm5iZiI6MTcxNDA5MjI4MSwicGF0aCI6Ii8xMzY2NDA5NzAvMzI1NzE4NjM3LTcxNmJhZDNhLTRmYWEtNDkwYi1hNWMzLTEyMDM5YzYzY2Y4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwMDQ0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTRmOWUzNmQ5YmE1MDRmOTQzZjc5MDI5OTNjNDhlY2IyYjcwNDRlNmYxMmVmMzhkYTYxNThmOGJjNmE4OWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F9zfPTvi9JeOgcjc9iBKw7RyHN3W05zPCEPL9K2fTaE)

目录填写问题 具体修改参考 #10
