### ISSUE TITLE
无法启动后端，提示找不到app.helper.sites模块

### ISSUE THREAD

**Issue by Ailina0728** [developer-wlj/Windows-MoviePilot#16]
环境是windows server 2022，安装git版报错，无法启动后端程序，前端正常打开

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: C:\Windows-MoviePilot-Git\Python3.11\python.exe -m pip install --upgrade pip"
已自动为你打开了浏览器"
"启动后端中....."
Traceback (most recent call last):
    File "C:\Windows-MoviePilot-Git\MoviePilot\app\main.py", line 23, in <module>
       from app.core.plugin import PluginManager
    File "C:\Windows-MoviePilot-Git\MoviePilot\app\core\plugin.py", line 19, in <module>
       from app.helper.sites import SitesHelper
ModuleNotFoundError: No module named 'app.helper.sites'

**Comment by developer-wlj** [comment]
只有一种情况, 第一次安装 Git报错了, 导致准备的文件没正确释放 可以下载https://github.com/jxxghp/MoviePilot-Resources/blob/main/resources/user.sites.bin 和 https://github.com/jxxghp/MoviePilot-Resources/blob/main/resources/sites.cp311-win_amd64.pyd 这两个文件 复制到 app/helper 目录中 或者删除 C:\Windows-MoviePilot-Git 目录 重新释放文件

**Comment by Ailina0728** [comment]
> 只有一种情况, 第一次安装 Git报错了, 导致准备的文件没正确释放 可以下载https://github.com/jxxghp/MoviePilot-Resources/blob/main/resources/user.sites.bin 和 https://github.com/jxxghp/MoviePilot-Resources/blob/main/resources/sites.cp311-win_amd64.pyd 这两个文件 复制到 app/helper 目录中 或者删除 C:\Windows-MoviePilot-Git 目录 重新释放文件

是的大佬，按照你给的方法确实解决了问题。那么这个版本后端启动后任务栏没有图标的吗？然后cmd窗口需要常驻，关闭cmd则等于关闭了后端，是这样不？

**Comment by developer-wlj** [comment]
目前是这样的 我没有win11平台测试 在第一次启动可能会报错 只能前端运行显示错误. 后期稳定在改到后台
