### ISSUE TITLE
关于开机无法自启动的问题

### ISSUE THREAD

**Issue by eatumom** [developer-wlj/Windows-MoviePilot#18]
把自动生成moviepilot的快捷方式放入windows的启动文件夹无法开机自启
手动运行moviepilot的快捷方式可以运行
用bat命令运行moviepilot程序提示Windows 找不到文件'trayservice.exe’。请确定文件名是否正确后，再试一次。

**Comment by developer-wlj** [comment]
被防护系统拦截了，加入白名单，再次安装，重新运行

**Comment by developer-wlj** [comment]
哦! 没仔细看问题
- 如果你用bat运行 需要先切换到moviepilot.exe的当前目录,不能以绝对路径运行,否则就会出现找不到文件'trayservice.exe’,或者快捷方式-高级-用管理员身份运行
- 快捷方式放入启动文件夹不能自启动,大概你启用了UAC, 无法以管理员身份启动,如果你使用UAC,可以考虑用计划任务实现自启或者快捷方式-高级-用管理员身份运行

**Comment by eatumom** [comment]
好的感谢
