### ISSUE TITLE
1.9.12.84e6abb打开后几秒钟闪退

### ISSUE THREAD

**Issue by yeluonight** [developer-wlj/Windows-MoviePilot#22]
运行main.py，有个error如下：
ERROR:    [Errno 13] error while attempting to bind on address ('0.0.0.0', 3001): 以一种访问权限不允许的方式做了一个访问套接字的尝试。

完整的输出如下：
D:\MoviePilot\project\MoviePilot>..\..\Python3.11\python .\app\main.py
D:\MoviePilot\project\MoviePilot
[32mINFO[0m:     Started server process [[36m5904[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO:[0m    main.py - 站点资源版本：1.4.6
[32mINFO:[0m    main.py - 认证资源版本：1.3.2
[32mINFO:[0m    main.py - hdfans 用户认证成功！
INFO:    module.py - Moudle Loaded：BangumiModule
INFO:    module.py - Moudle Loaded：DoubanModule
INFO:    module.py - Moudle Loaded：FanartModule
INFO:    module.py - Moudle Loaded：FileTransferModule
INFO:    module.py - Moudle Loaded：FilterModule
INFO:    module.py - Moudle Loaded：IndexerModule
INFO:    module.py - Moudle Loaded：JellyfinModule
INFO:    module.py - Moudle Loaded：SubtitleModule
INFO:    category.py - 已加载二级分类策略 category.yaml
INFO:    module.py - Moudle Loaded：TheMovieDbModule
INFO:    module.py - Moudle Loaded：TheTvDbModule
INFO:    module.py - Moudle Loaded：TransmissionModule
INFO:    module.py - Moudle Loaded：WechatModule
INFO:    plugin.py - 开始安装第三方插件...
INFO:    plugin.py - 共获取到 109 个线上插件
INFO:    plugin.py - 第三方插件安装完成
INFO:    plugin.py - 加载插件：AutoSignIn 版本：2.4
INFO:    plugin.py - 加载插件：ConfigCenter 版本：2.6
INFO:    customsites - 开始同步CookieCloud站点 ...
INFO:    customsites - 自定义站点 Cookie同步成功：更新了0个站点，总1个站点
INFO:    plugin.py - 加载插件：CustomSites 版本：1.0
INFO:    removelink - Hello, RemoveLink! config {}
INFO:    plugin.py - 加载插件：RemoveLink 版本：2.2
INFO:    plugin.py - 加载插件：ContractCheck 版本：1.4
INFO:    plugin.py - 加载插件：SiteStatistic 版本：3.9.1
Pending jobs:
    站点未读消息 (trigger: cron[month='*', day='*', day_of_week='*', hour='9', minute='25'], pending)
INFO:    plugin.py - 加载插件：SiteUnreadMsg 版本：1.9
INFO:    plugin.py - 加载插件：DownloadSiteTag 版本：2.1
INFO:    plugin.py - 加载插件：SiteRefresh 版本：1.2
INFO:    plugin.py - 加载插件：DoubanSync 版本：1.8
INFO:    plugin.py - 加载插件：CloudLinkMonitor 版本：2.4.6
INFO:    dirmonitor - E:\PT下载 的目录监控服务启动
INFO:    dirmonitor - E:\导入媒体库 的目录监控服务启动
INFO:    dirmonitor - E:\导入媒体库\115\电影\林正英 的目录监控服务启动
Pending jobs:
    DirMonitor.send_msg (trigger: interval[0:00:15], pending)
INFO:    plugin.py - 加载插件：DirMonitor 版本：2.4
INFO:    plugin.py - 加载插件：LinkMonitor 版本：1.6
INFO:    plugin.py - 加载插件：Cd2Assistant 版本：1.6
INFO:    plugin.py - 加载插件：LibraryScraper 版本：1.5
INFO:    plugin.py - 加载插件：TorrentRemover 版本：1.2.2
INFO:    plugin.py - 加载插件：MediaSyncDel 版本：1.7
INFO:    plugin.py - 加载插件：CustomHosts 版本：1.1
INFO:    plugin.py - 加载插件：FileSoftLink 版本：1.9.8
INFO:    plugin.py - 加载插件：RemoteIdentifiers 版本：2.2
INFO:    plugin.py - 加载插件：SpeedLimiter 版本：1.2
INFO:    plugin.py - 加载插件：CloudflareSpeedTest 版本：1.4
INFO:    plugin.py - 加载插件：BestFilmVersion 版本：2.3
INFO:    plugin.py - 加载插件：MediaServerMsg 版本：1.2
INFO:    plugin.py - 加载插件：MediaServerRefresh 版本：1.2
INFO:    plugin.py - 加载插件：WebHook 版本：1.0
INFO:    plugin.py - 加载插件：AutoBackup 版本：1.3
INFO:    plugin.py - 加载插件：CrossSeed 版本：2.3
INFO:    plugin.py - 加载插件：IYUUAutoSeed 版本：1.9.3
INFO:    plugin.py - 加载插件：SyncDownloadFiles 版本：1.1
INFO:    plugin.py - 加载插件：BrushFlow 版本：3.4
INFO:    plugin.py - 加载插件：DownloadingMsg 版本：1.1
INFO:    plugin.py - 加载插件：InvitesSignin 版本：1.4
INFO:    plugin.py - 加载插件：PersonMeta 版本：1.4
INFO:    plugin.py - 加载插件：ActorSubscribe 版本：2.1
INFO:    plugin.py - 加载插件：IyuuMsg 版本：1.2
INFO:    plugin.py - 加载插件：CloudDiskDel 版本：1.3
INFO:    plugin.py - 加载插件：CloudStrm 版本：4.4
INFO:    plugin.py - 加载插件：CloudStrmIncrement 版本：1.1
INFO:    plugin.py - 加载插件：ShortPlayMonitor 版本：3.2
INFO:    plugin.py - 加载插件：StrmConvert 版本：1.0
INFO:    plugin.py - 加载插件：DownloadTorrent 版本：1.0
Pending jobs:
    订阅下载统计 (trigger: cron[month='*', day='*', day_of_week='*', hour='1', minute='5'], pending)
INFO:    plugin.py - 加载插件：SubscribeStatistic 版本：1.6
INFO:    plugin.py - 加载插件：CustomIndexer 版本：1.0
INFO:    plugin.py - 加载插件：TrackerEditor 版本：1.5
INFO:    plugin.py - 加载插件：FFmpegThumb 版本：1.2
INFO:    downloaderhelper - 尝试停止插件服务...
INFO:    downloaderhelper - 尝试停止插件服务调度器...
INFO:    downloaderhelper - 插件未启用服务调度器，无须停止
INFO:    downloaderhelper - 尝试清除插件缓存...
INFO:    downloaderhelper - 插件未启用缓存，无须清除
INFO:    downloaderhelper - 插件服务停止完成
INFO:    downloaderhelper - 插件配置加载完成：None
INFO:    plugin.py - 加载插件：DownloaderHelper 版本：2.8
INFO:    plugin.py - 加载插件：MergeSiteSwitch 版本：1.1
Pending jobs:
    插件自动更新 (trigger: cron[month='*', day='*', day_of_week='*', hour='1', minute='5'], pending)
INFO:    plugin.py - 加载插件：PluginAutoUpdate 版本：1.9.2
INFO:    plugin.py - 加载插件：MPServerStatus 版本：1.0
INFO:    scheduler.py - 注册插件站点自动签到服务：站点自动签到服务 - interval
INFO:    scheduler.py - 注册插件站点数据统计服务：站点数据统计服务 - cron[month='*', day='*', day_of_week='*', hour='1', minute='5']
INFO:    scheduler.py - 注册插件媒体库刮削服务：媒体库刮削 - cron[month='*', day='*/7', day_of_week='*', hour='0', minute='0']
INFO:    scheduler.py - 注册插件共享识别词服务：获取远端识别词 - cron[month='*', day='*', day_of_week='*', hour='4', minute='30']
INFO:    scheduler.py - 注册插件播放限速服务：播放限速检查服务 - interval
INFO:    scheduler.py - 注册插件自动备份服务：自动备份定时服务 - cron[month='*', day='*', day_of_week='*', hour='4', minute='40']
INFO:    scheduler.py - 注册插件青蛙辅种助手服务：青蛙辅种助手 - cron
INFO:    brushflow - 站点刷流Brush定时服务启动，时间间隔 10 分钟
INFO:    brushflow - 站点刷流Check定时服务启动，时间间隔 5 分钟
INFO:    scheduler.py - 注册插件站点刷流服务：站点刷流Brush服务 - interval
INFO:    scheduler.py - 注册插件站点刷流服务：站点刷流Check服务 - interval
INFO:    scheduler.py - 注册插件下载进度推送服务：下载进度推送服务 - interval
INFO:    scheduler.py - 注册插件药丸签到服务：药丸签到服务 - cron[month='*', day='*', day_of_week='*', hour='9', minute='0']
INFO:    scheduler.py - 注册插件演职人员刮削服务：演职人员刮削服务 - cron[month='*', day='*', day_of_week='*', hour='1', minute='10']
Pending jobs:
    同步CookieCloud站点 (trigger: interval[1 day, 0:00:00], next run at: 2024-07-28 08:43:06 CST)
    同步媒体服务器 (trigger: interval[6:00:00], next run at: 2024-07-28 08:47:06 CST)
    新增订阅搜索 (trigger: interval[0:05:00], pending)
    订阅元数据更新 (trigger: interval[6:00:00], pending)
    订阅刷新 (trigger: cron[hour='7', minute='21'], pending)
    订阅刷新 (trigger: cron[hour='7', minute='44'], pending)
    订阅刷新 (trigger: cron[hour='8', minute='19'], pending)
    订阅刷新 (trigger: cron[hour='8', minute='46'], pending)
    订阅刷新 (trigger: cron[hour='9', minute='10'], pending)
    订阅刷新 (trigger: cron[hour='9', minute='39'], pending)
    订阅刷新 (trigger: cron[hour='10', minute='6'], pending)
    订阅刷新 (trigger: cron[hour='10', minute='45'], pending)
    订阅刷新 (trigger: cron[hour='11', minute='10'], pending)
    订阅刷新 (trigger: cron[hour='11', minute='46'], pending)
    订阅刷新 (trigger: cron[hour='12', minute='10'], pending)
    订阅刷新 (trigger: cron[hour='12', minute='39'], pending)
    订阅刷新 (trigger: cron[hour='13', minute='12'], pending)
    订阅刷新 (trigger: cron[hour='13', minute='38'], pending)
    订阅刷新 (trigger: cron[hour='14', minute='11'], pending)
    订阅刷新 (trigger: cron[hour='14', minute='34'], pending)
    订阅刷新 (trigger: cron[hour='15', minute='8'], pending)
    订阅刷新 (trigger: cron[hour='15', minute='32'], pending)
    订阅刷新 (trigger: cron[hour='15', minute='53'], pending)
    订阅刷新 (trigger: cron[hour='16', minute='22'], pending)
    订阅刷新 (trigger: cron[hour='16', minute='54'], pending)
    订阅刷新 (trigger: cron[hour='17', minute='27'], pending)
    订阅刷新 (trigger: cron[hour='17', minute='54'], pending)
    订阅刷新 (trigger: cron[hour='18', minute='31'], pending)
    订阅刷新 (trigger: cron[hour='19', minute='10'], pending)
    订阅刷新 (trigger: cron[hour='19', minute='32'], pending)
    订阅刷新 (trigger: cron[hour='20', minute='4'], pending)
    订阅刷新 (trigger: cron[hour='20', minute='30'], pending)
    订阅刷新 (trigger: cron[hour='21', minute='0'], pending)
    订阅刷新 (trigger: cron[hour='21', minute='28'], pending)
    订阅刷新 (trigger: cron[hour='21', minute='54'], pending)
    订阅刷新 (trigger: cron[hour='22', minute='28'], pending)
    下载文件整理 (trigger: interval[0:05:00], pending)
    壁纸缓存 (trigger: interval[0:30:00], next run at: 2024-07-28 08:42:09 CST)
    公共定时服务 (trigger: interval[0:10:00], pending)
    缓存清理 (trigger: interval[3 days, 0:00:00], pending)
    用户认证检查 (trigger: interval[0:10:00], pending)
    站点自动签到服务 (trigger: interval[8:00:00], pending)
    站点数据统计服务 (trigger: cron[month='*', day='*', day_of_week='*', hour='1', minute='5'], pending)
    媒体库刮削 (trigger: cron[month='*', day='*/7', day_of_week='*', hour='0', minute='0'], pending)
    获取远端识别词 (trigger: cron[month='*', day='*', day_of_week='*', hour='4', minute='30'], pending)
    播放限速检查服务 (trigger: interval[0:01:00], pending)
    自动备份定时服务 (trigger: cron[month='*', day='*', day_of_week='*', hour='4', minute='40'], pending)
    青蛙辅种助手 (trigger: cron[hour='4', minute='18'], pending)
    站点刷流Brush服务 (trigger: interval[0:10:00], pending)
    站点刷流Check服务 (trigger: interval[0:05:00], pending)
    下载进度推送服务 (trigger: interval[1:00:00], pending)
    药丸签到服务 (trigger: cron[month='*', day='*', day_of_week='*', hour='9', minute='0'], pending)
    演职人员刮削服务 (trigger: cron[month='*', day='*', day_of_week='*', hour='1', minute='10'], pending)
INFO:     Application startup complete.
ERROR:    [Errno 13] error while attempting to bind on address ('0.0.0.0', 3001): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
INFO:     Waiting for application shutdown.
INFO:    module.py - 正在停止所有模块...
INFO:    module.py - Moudle Stoped：BangumiModule
INFO:    module.py - Moudle Stoped：DoubanModule
INFO:    module.py - Moudle Stoped：FanartModule
INFO:    module.py - Moudle Stoped：FileTransferModule
INFO:    module.py - Moudle Stoped：FilterModule
INFO:    module.py - Moudle Stoped：IndexerModule
INFO:    module.py - Moudle Stoped：JellyfinModule
INFO:    module.py - Moudle Stoped：SubtitleModule
INFO:    module.py - Moudle Stoped：TheMovieDbModule
INFO:    module.py - Moudle Stoped：TheTvDbModule
INFO:    module.py - Moudle Stoped：TransmissionModule
INFO:    module.py - Moudle Stoped：WechatModule
INFO:    module.py - 模块停止完成
INFO:    plugin.py - 正在停止所有插件...
INFO:    downloaderhelper - 尝试停止插件服务...
INFO:    downloaderhelper - 尝试停止插件服务调度器...
INFO:    downloaderhelper - 插件未启用服务调度器，无须停止
INFO:    downloaderhelper - 尝试清除插件缓存...
INFO:    downloaderhelper - 插件未启用缓存，无须清除
INFO:    downloaderhelper - 插件服务停止完成
INFO:    plugin.py - 插件停止完成
INFO:    command.py - 正在停止事件处理...
INFO:    command.py - 事件处理停止完成
INFO:    scheduler.py - 正在停止定时任务...
INFO:    scheduler.py - 定时任务停止完成
INFO:     Application shutdown complete.

D:\MoviePilot\project\MoviePilot>

**Comment by developer-wlj** [comment]
3001端口被占用了，重启电脑即可，如果你有别的服务，优先启动MP
