### ISSUE TITLE
我设置了不分类，但是下载后自动整理还是会给自动创建个华语电影二级目录

### ISSUE THREAD

**Issue by bugleigt** [developer-wlj/Windows-MoviePilot#23]
我关闭了自动分类，但是通过mp下载电影后自动整理媒体库还是会自动创建一个二级目录。
![{DCFD7A82-0C88-4096-AD90-FC70940D87CB}](https://github.com/user-attachments/assets/00ee4ab8-c179-48a8-bdbf-da1bcd96e98b)
![{30E755E4-7DEB-4E48-9504-922B16ED12ED}](https://github.com/user-attachments/assets/370b9326-349b-431c-bf2c-a8293e7639c8)
![{E0B3A9C8-BFDE-411A-884E-8993A27ACC90}](https://github.com/user-attachments/assets/1e2ca978-e5e4-4a07-b81f-58782c1a95d4)
请问一下这是哪里设置有问题吗？

**Comment by bugleigt** [comment]
![{3728095E-04CA-4E28-921E-775AC6F707A1}](https://github.com/user-attachments/assets/d6d21828-19a6-487e-9002-def577fa75ab)

**Comment by developer-wlj** [comment]
不支持从配置中心进行设置，需要手动修改appWindows.env而不是app.env

**Comment by bugleigt** [comment]
=  =  我这边试了好久都没发现问题，最后发现原来后台还有个nastools在做目录转移 = = 谢谢大佬。
再弱弱的问一句，请问win版能修改访问端口吗？
想把端口号改到后面去一点，之前5000端口被dx扫过一次然后给我把宽带封了，虽然现在没用公网IPV4，用的是IPV6，但是想着改到5位数稳妥一些。
我试着把nginx.conf文件的端口更改后发现网页无法加载
![{00D5CE19-8CCD-428E-96F3-95A1F835FB24}](https://github.com/user-attachments/assets/4fcc7663-5ca8-4b52-8842-e8414d3e6282)
