### ISSUE TITLE
1.9.15.2153ad4版本 从appWindows.env 插件变量填加多个地址不生效

### ISSUE THREAD

**Issue by eatumom** [developer-wlj/Windows-MoviePilot#24]
变量填写为
PLUGIN_MARKET=https://github.com/jxxghp/MoviePilot-Plugins,https://github.com/thsrite/MoviePilot-Plugins,https://github.com/honue/MoviePilot-Plugins,https://github.com/InfinityPacer/MoviePilot-Plugins,https://github.com/dandkong/MoviePilot-Plugins,https://github.com/Aqr-K/MoviePilot-Plugins,https://github.com/AnjoyLi/MoviePilot-Plugins,https://github.com/WithdewHua/MoviePilot-Plugins,https://github.com/HankunYu/MoviePilot-Plugins,https://github.com/baozaodetudou/MoviePilot-Plugins,https://github.com/almus2zhang/MoviePilot-Plugins,https://github.com/Pixel-LH/MoviePilot-Plugins,https://github.com/lightolly/MoviePilot-Plugins,https://github.com/suraxiuxiu/MoviePilot-Plugins,https://github.com/gxterry/MoviePilot-Plugins,https://github.com/hotlcc/MoviePilot-Plugins-Third,https://github.com/boeto/MoviePilot-Plugins,https://github.com/xiangt920/MoviePilot-Plugins,https://github.com/xcehnz/MoviePilot-Plugins,https://github.com/yideng966/MoviePilot-Plugins,https://github.com/loongcheung/MoviePilot-Plugins,https://github.com/kanekicany/MoviePilot-Plugins,https://github.com/zoffyultraman/MoviePilot-Plugins,https://github.com/dadinet/MoviePilot-Plugins,https://github.com/imaliang/MoviePilot-Plugins/

**Comment by developer-wlj** [comment]
日志呢！没日志就大致判断了
1，是否填写IS_ENABLED_REMOTE_REPO=true的变量，默认是关闭的
2，连接github网络不好
我更倾向于是第一种情况

**Comment by eatumom** [comment]
没看到这个启用远程仓库的变量 怪不得启动日志没有关于插件仓库的输出 我的我的

**Comment by eatumom** [comment]
没看到这个启用远程仓库的变量 怪不得启动日志没有关于插件仓库的输出 我的我的
