### ISSUE TITLE
下载目录的分类设置为全部时，设置无法生效

### ISSUE THREAD

**Issue by yuki-216** [developer-wlj/Windows-MoviePilot#25]
web页面的设定，目录，下载目录设置完全不生效
![image](https://github.com/user-attachments/assets/526a557d-b4f3-451d-8463-7df15b7c0223)
媒体库目录是正确的使用了web页面里的设定，虽然在appWindows.env中也没有更新。
![image](https://github.com/user-attachments/assets/55521b61-6a30-4701-be40-ff421401e886)
下载库目录同样的没有更新到appWindows.env
![image](https://github.com/user-attachments/assets/f814ddac-4cd9-4453-9b95-fc3403d5ac59)
bug情况，原本我已经在web设定中添加了多个目录，比如“E:/bt/影视”，“G:/bt/影视”，但我今天才发现，即使我移动了排序，他都始终会下载到”E:/bt/影视“这个目录下面。然后我选择在web设定中，删掉了”E:/bt/影视“，保留了”G:/bt/影视”。直接下载失败，提示无下载目录。
目前即使我在web设定中添加回了“E:/bt/影视”，也无法下载。

**Comment by developer-wlj** [comment]
什么版本 有报错日志没有
原MP作者做了改动, web设置的有些变量不会再保存到appWinodows.env文件,而是保存到数据库中,如果你会db操作可在数据库看到,至于你说的无法下载和下载到旧目录,可能有bug,我记得媒体类型这里不能选全部,要有具体的类型,媒体类别可以全部,或者重启看看

**Comment by yuki-216** [comment]
前后端都是最新版本，我也发现确实是在数据库中保存了。但问题是，现在新的web设置的下载目录变量似乎不会更新到数据库中。甚至我尝试了全部重装，全新的appwindows.env 和user.db，仍然无法下载。报错日志，均为未找到下载目录。

**Comment by yuki-216** [comment]
根据你的解答，我将下载目录分类更改为电影和电视剧，就可以使用。但我认为这仍然是一个bug，而不是feature；希望能解决这个问题，或者告知一下，不能分类设置为全部，我不清楚这是原版mp的问题，还是windows-moviepilot的问题。

**Comment by yuki-216** [comment]
由此看来，只有设置为具体的分类，才会注入到数据库中保存

**Comment by developer-wlj** [comment]
原mp的bug
