### ISSUE TITLE
关于开机自启

### ISSUE THREAD

**Issue by zjzlh1** [developer-wlj/Windows-MoviePilot#28]
我发现在计划任务里面设置开机自动启动exe文件，只会在托盘运行一个mp的图标，后台并没有实际在运行，web也进不去。是为什么

**Comment by developer-wlj** [comment]
如果windows-mp安装到系统盘，需要管理员权限运行，否则会计划任务会一直后台重启，现象就是托盘栏有图标，实际权限不足，导致进程退出，任务计划又重新启动进程
