### ISSUE TITLE
无法自启动

### ISSUE THREAD

**Issue by peaynan** [developer-wlj/Windows-MoviePilot#29]
添加到startup文件夹或者计划程序都无法实现自启动，同时会显示
Windows找不到文件'trayservice,exe'。请确定文件名是否正确后，再试一次。

我安装在c盘，在D盘目录下通过资源管理器的地址栏直接地址运行moviepilot.exe也会显示
Windows找不到文件'trayservice,exe'。请确定文件名是否正确后，再试一次。

不知道为什么，正常双击可以正常运行

希望可以提供能够正常自启动的方法

**Comment by peaynan** [comment]
抱歉没有先看其他issue

**Comment by shua1zh** [comment]
请问看的哪个issue啊，求方法

**Comment by peaynan** [comment]
> 请问看的哪个issue啊，求方法

https://github.com/developer-wlj/Windows-MoviePilot/issues/18#issuecomment-2172544786
