### ISSUE TITLE
希望更新时保留原有的nginx配置文件

### ISSUE THREAD

**Issue by yuki-216** [developer-wlj/Windows-MoviePilot#32]
C:\Program Files (x86)\MoviePilot\Nginx1.15.11\conf\vhosts\mp_v2.conf 希望检测mp_v2.conf是否已存在，存在就不覆盖。不然每次更新都要自己手动再改下端口，因为更换了常规端口，放到公网

**Comment by developer-wlj** [comment]
可以复制一份mp_v2.conf，并重命名为不包含中文和特殊字符的名称，如new_mp_v2.conf，nginx会扫描所有后缀.conf的配置文件，之后的升级安装也不会覆盖用户手动创建的文件。

**Comment by yuki-216** [comment]
已收到（自动回复）

**Comment by yuki-216** [comment]
感谢你的回复，我尝试这么做看看；这是我查询到的相关信息，在 include vhosts/*.conf 引入的多个配置文件中，Nginx 通常会按文件名的字典顺序（ASCII）进行加载和解析，因此文件名排序在前的配置文件会先被加载。

对于你的示例，mp_v2.conf 会在 new_mp_v2.conf 之前加载。如果这两个文件中有重叠的配置（如相同的 server_name 或 location），Nginx 会使用后加载的文件中的设置，即 new_mp_v2.conf 中的配置会覆盖 mp_v2.conf 中的配置。

因此，配置文件的优先级取决于加载顺序：后加载的文件会优先。
