### ISSUE TITLE
对win10支持

### ISSUE THREAD

**Issue by 980810932** [developer-wlj/Windows-MoviePilot#34]
请问大佬，V2.0不支持win10安装吗，我有朋友和我一起实验了，win11可以正常启动，但是win10下就不行。

**Comment by developer-wlj** [comment]
你能看看README吗，按README操作了吗？日志呢？错误呢？

**Comment by 980810932** [comment]
1、我确实看了你git里面的readme，那个C++我是有的，那个python我也有，如果你说其他问题，我只能说抱歉，我过于小白，没get到，还望指教。
2、我双击图标后，右下角没有出现运行的图标，所以我不知道可有log，我也没想起来去文件夹里看看。按照我粗浅的理解，那个log应该是成功运行后自动生成首次随机密码，但是我在10下托盘图标都没看到，我盲猜可能没有日志，等我回家后找个win10电脑再试试。
3、我升级到win11（保留所有软件文件升级）后，我重新安装后就能正常运行了。未进行其他操作。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: developer-wlj ***@***.***&gt;
发送时间: 2024年11月13日 13:37
收件人: developer-wlj/Windows-MoviePilot ***@***.***&gt;
抄送: 980810932 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [developer-wlj/Windows-MoviePilot] 对win10支持 (Issue #34)





 
你能看看README吗，按README操作了吗？日志呢？错误呢？

**Comment by 980810932** [comment]
我又找了一台win10没安装过mp的电脑试了，成功运行了，到底啥情况我也不知道了，安装失败的电脑已经升级win11也成功了，无法回到原来那样排查原因了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: developer-wlj ***@***.***&gt;
发送时间: 2024年11月13日 13:37
收件人: developer-wlj/Windows-MoviePilot ***@***.***&gt;
抄送: 980810932 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [developer-wlj/Windows-MoviePilot] 对win10支持 (Issue #34)





 
你能看看README吗，按README操作了吗？日志呢？错误呢？
