### ISSUE TITLE
从2.0.4开始，设置-存储和目录显示为空

### ISSUE THREAD

**Issue by shua1zh** [developer-wlj/Windows-MoviePilot#35]
![wechat_2024-11-15_154250_346](https://github.com/user-attachments/assets/625a4ab9-1c1d-4424-a2cd-c242cba1c29b)

**Comment by developer-wlj** [comment]
啊，我只提供windows运行环境，代码没做更改，可能自动打包打进去bug了，等待重新打包即可，还有如果现有功能够用，不要升级！！！
