### ISSUE TITLE
请问要怎么更改默认的端口呢？

### ISSUE THREAD

**Issue by keeper-0** [developer-wlj/Windows-MoviePilot#36]
我尝试在环境变量和app.env中修改端口配置，但似乎没有起作用，依然是使用的3111，3333端口。不知道是不是端口的原因，我这收不到jellyfin/emby的webhook信息，希望能够修改回3001端口试试
![image](https://github.com/user-attachments/assets/474ac8c9-760c-4161-b58b-e6d2edba0026)

**Comment by developer-wlj** [comment]
参考 #32
