### ISSUE TITLE
python: can't open file 'D:\\MoviePilotV2\\project\\app\\main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by piaoyun** [developer-wlj/Windows-MoviePilot#39]
D:\MoviePilotV2\project>python .\app\main.py
python: can't open file 'D:\\MoviePilotV2\\project\\app\\main.py': [Errno 2] No such file or directory

运行直接报错。。。

**Comment by developer-wlj** [comment]
你这明显目录不对，应该进入D:\MoviePilotV2\project\MoviePilot目录
还有你命令执行也不对，应该是..\..\Python3.11\python .\app\main.py
而不是python .\app\main.py
