### ISSUE TITLE
目录无法更改

### ISSUE THREAD

**Issue by Yustyn555** [developer-wlj/Windows-MoviePilot#4]

**Comment by developer-wlj** [comment]
怎么配置?通过系统环境变量?还是文件.env还是config.py?

**Comment by developer-wlj** [comment]
> > 怎么配置的?通过系统环境变量?还是文件.env还是config.py?
> 
> env文件
> 比如说我需要把媒体设为
> LIBRARY_PATH=D: \VIDEO或者
> LIBRARY_PATH=r''D: \VIDEO''都识别不了。

这个是媒体库路径变量！使用文件管理和下载路径，需要填写DOWNLOAD_PATH变量，路径按照模板抄就行

**Comment by Yustyn555** [comment]
大佬，没看见模板呢
