### ISSUE TITLE
MP运行大概一天后退出

### ISSUE THREAD

**Issue by sdepool** [developer-wlj/Windows-MoviePilot#5]
MP版本：1.4.8-1，运行大概一两天后退出，貌似是刷新站点数据的时候退出。平时刷新站点数据是正常的。以前版本也有这个问题

MP的log：
【INFO】2023-12-06 08:54:03,354 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2023-12-06 08:54:08,316 - transfer.py - 没有获取到已完成的下载任务
【INFO】2023-12-06 08:59:03,355 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2023-12-06 08:59:08,279 - transfer.py - 没有获取到已完成的下载任务
【INFO】2023-12-06 09:04:03,355 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2023-12-06 09:04:08,340 - transfer.py - 没有获取到已完成的下载任务
【INFO】2023-12-06 09:09:03,356 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2023-12-06 09:09:08,421 - transfer.py - 没有获取到已完成的下载任务
【INFO】2023-12-06 09:10:00,023 - sitestatisticnomsg - 开始刷新站点数据 ...

Windows server 2022 事件：
错误应用程序名称: python.exe，版本: 3.11.4150.1013，时间戳: 0x64801a28
错误模块名称: etree.cp311-win_amd64.pyd，版本: 0.0.0.0，时间戳: 0x64a53f33
异常代码: 0xc0000005
错误偏移量: 0x00000000001bedff
错误进程 ID: 0xdf4
错误应用程序启动时间: 0x01da276681e76f91
错误应用程序路径: D:\Program Files (x86)\MoviePilot\Python3.11\python.exe
错误模块路径: D:\Program Files (x86)\MoviePilot\Python3.11\Lib\site-packages\lxml\etree.cp311-win_amd64.pyd
报告 ID: f1b57614-cce2-48e2-84c8-ad46fc6d10df
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by developer-wlj** [comment]
如果你的日志没有给错, 站点数据统计插件确实使用了etree模块, 在多线程的情况 可能会导致python进程退出. 可以向该插件作者进行反馈, 我只是搭建win运行环境, 核心代码没有改动 目前可以给几条建议
1. 在该插件配置列队数量栏中 默认5 改为 1
2. 如果频繁python进程退出, 可以先不使用该插件,等插件作者该改进
