### ISSUE TITLE
配置站点认证应该如何填写appWindows.env呢

### ISSUE THREAD

**Issue by yeluonight** [developer-wlj/Windows-MoviePilot#6]
尝试了直接添加
AUTH_SITE=iyuu
IYUU_SIGN=IYUU................
以及
AUTH_SITE:iyuu
IYUU_SIGN:IYUU................
在log里均提示 singleton.py - 站点认证参数未设置，无法进行用户认证！

**Comment by yeluonight** [comment]
目前是修改MoviePilot\project\MoviePilot\app\core\config.py里的内容进行认证

**Comment by developer-wlj** [comment]
我这边测试，没问题
请根据以下思路进行排查
1，检查下配置appWindows.env文件是否拼写正确
2，是否在系统环境变量设置为空的变量，如有多余的，自行删除
