### ISSUE TITLE
请问怎么修改默认端口号.改了环境变量不行.谢谢

### ISSUE THREAD

**Issue by Bender1337** [developer-wlj/Windows-MoviePilot#7]
外网用IPV6的免费域名,然后访问不了3000端口.请问怎么修改默认端口号.改了环境变量不行.

**Comment by developer-wlj** [comment]
需要修改nginx配置
先停用nginx
然后找到Nginx1.15.11\conf\vhosts\目录下 有个.conf文件 
打开文件 找到
listen 3000;在下面添加一行
listen [::]:3000;
保存即可

**Comment by 361586** [comment]
> > 需要修改nginx配置 先停用nginx 然后找到Nginx1.15.11\conf\vhosts\目录下 有个.conf文件 打开文件 找到 listen 3000;在下面添加一行 listen [::]:3000; 保存即可
> 
> 请问api端口在哪里改呢，我知道默认的是3001

我看到了，也是在这个.conf文件里
