### ISSUE TITLE
appWindows.env无法添加多个站点认证

### ISSUE THREAD

**Issue by yeluonight** [developer-wlj/Windows-MoviePilot#8]
只添加单个站点是可以正常认证，比如AUTH_SITE=iyuu则可以认证，但是如果我填写AUTH_SITE=iyuu,icc2022，则这两个都无法进行认证（IYUU_SIGN和ICC2022_UID、ICC2022_PASSKEY都已填写）
![屏幕截图 2024-03-07 145509](https://github.com/developer-wlj/Windows-MoviePilot/assets/31738833/7297d678-0050-42c4-8447-4f884ba614fd)

log如下：
【ERROR】2024-03-07 14:54:03,184 - singleton.py - 环境变量 IYUU_SIGN 未设置！
【ERROR】2024-03-07 14:54:03,340 - singleton.py - iyuu认证出错：非法请求：缺少必要参数sign
【ERROR】2024-03-07 14:54:03,350 - singleton.py - 环境变量 ICC2022_UID 未设置！
【ERROR】2024-03-07 14:54:03,359 - singleton.py - 环境变量 ICC2022_PASSKEY 未设置！

**Comment by developer-wlj** [comment]
已修复, 下载最新版本即可
