### ISSUE TITLE
我去....我好像成功的添加了环境变量在win上完成了认证....

### ISSUE THREAD

**Issue by SoTender** [developer-wlj/Windows-MoviePilot#9]
官方wiki好像没有讲win版如何添加环境变量。

以hhclub为例：

AUTH_SITE=hhclub
HHCLUB_USERNAME=用户名
HHCLUB_PASSKEY=密钥

先存记事本

然后再win里搜索：
编辑系统环境变量>环境变量>系统变量

添加上面那对应三项就可以了
PS：用户名和密钥换成自己的！

![image](https://github.com/developer-wlj/Windows-MoviePilot/assets/127156952/161418cb-cfc6-4cbe-8445-a17fb11edfcc)

**Comment by SoTender** [comment]
不过好像这个跟本项目没有太大的关系。反正稀里糊涂的旧搜到这里了，后来想了

**Comment by wenjuhe811** [comment]
谢谢，我也认证上了

**Comment by MAX20081314** [comment]
怎么操作的，新手不懂
